### ISSUE TITLE
Numbered list example

### ISSUE THREAD

**Issue by madmaxio** [bokuweb/docx-rs#178]
Can you please provide numbered list example?

My experiments with numberings doesn't help much.

**Comment by bokuweb** [comment]
@madmaxio Please see https://github.com/bokuweb/docx-rs/blob/master/docx-core/examples/numbering.rs

**Comment by madmaxio** [comment]
Yes, but how to get two levels with 1 and 2 ? At the moment I use this code:

`use docx_rs::*;

pub fn main() -> Result<(), DocxError> {
    let path = std::path::Path::new("./numbering.docx");
    let file = std::fs::File::create(&path).unwrap();
    Docx::new()
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("Hello"))
                .numbering(NumberingId::new(2), IndentLevel::new(0)),
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("Hello"))
                .numbering(NumberingId::new(2), IndentLevel::new(1)),
        )
        .add_abstract_numbering(
            AbstractNumbering::new(2).add_level(
                Level::new(
                    0,
                    Start::new(1),
                    NumberFormat::new("decimal"),
                    LevelText::new("Section %1."),
                    LevelJc::new("left"),
                )
                .indent(
                    Some(1620),
                    Some(SpecialIndentType::Hanging(320)),
                    None,
                    None,
                ),
            ).add_level(
                Level::new(
                    1,
                    Start::new(2),
                    NumberFormat::new("decimal"),
                    LevelText::new("Section %1."),
                    LevelJc::new("left"),
                )
                .indent(
                    Some(1620),
                    Some(SpecialIndentType::Hanging(320)),
                    None,
                    None,
                ),
            )
            .add_level(
                Level::new(
                    2,
                    Start::new(2),
                    NumberFormat::new("decimal"),
                    LevelText::new("Section %2."),
                    LevelJc::new("left"),
                )
                .indent(
                    Some(1620),
                    Some(SpecialIndentType::Hanging(320)),
                    None,
                    None,
                ),
            )
        )
        .add_numbering(Numbering::new(2, 2))
        .build()
        .pack(file)?;
    Ok(())
}`

**Comment by bokuweb** [comment]
@madmaxio Thanks. What results do you expect to see?
A capture of the actual and expected results would be helpful

**Comment by madmaxio** [comment]
At the moment I get:

Section1. Hello
Section1. Hello

What I need is a numbered list:

1.Hello
2.Hello

**Comment by bokuweb** [comment]
@madmaxio try

``` rust
use docx_rs::*;

pub fn main() -> Result<(), DocxError> {
    let path = std::path::Path::new("./numbering.docx");
    let file = std::fs::File::create(&path).unwrap();
    Docx::new()
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("Hello"))
                .numbering(NumberingId::new(2), IndentLevel::new(0)),
        )
        .add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text("Hello"))
                .numbering(NumberingId::new(2), IndentLevel::new(0)),
        )
        .add_abstract_numbering(
            AbstractNumbering::new(2).add_level(
                Level::new(
                    0,
                    Start::new(1),
                    NumberFormat::new("decimal"),
                    LevelText::new("%1."),
                    LevelJc::new("left"),
                )
                .indent(
                    Some(1620),
                    Some(SpecialIndentType::Hanging(320)),
                    None,
                    None,
                ),
            ),
        )
        .add_numbering(Numbering::new(2, 2))
        .build()
        .pack(file)?;
    Ok(())
}
```

**Comment by madmaxio** [comment]
Worked perfectly, so you just added another paragraph I see...
