### ISSUE TITLE
Disable header if it not set

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bokuweb/docx-rs#327]
### Is your feature request related to a problem? Please describe.

Header is always visible. it is breaking table layout and can't be disabled inside rust

### Describe the solution you'd like

@bokuweb idea is to disable header if not set https://github.com/bokuweb/docx-rs/pull/115#issuecomment-903292373

### Additional context
![image](https://user-images.githubusercontent.com/46970457/130362500-cc93721c-3330-43b7-ab5a-c07a6ec797dc.png)

**Comment by bokuweb** [comment]
I'll fix it later

**Comment by bokuweb** [comment]
@sergeyshaykhullin Sorry for late, this issue is fixed by #369

**Comment by sergeyshaykhullin** [comment]
@bokuweb Does this fix will be a part of 0.3.1 release?

**Comment by bokuweb** [comment]
@sergeyshaykhullin yes. I'll publish it from now.

**Comment by bokuweb** [comment]
published. Please try 0.3.1
