### ISSUE TITLE
How to add arbitrary lines in single TableCell?

### ISSUE THREAD

**Issue by sinyo-matu** [bokuweb/docx-rs#511]
Hi everyone.
I want to create a table cell which contain arbitrary lines of content ( the number of lines are determined at runtime).

like 
| head|
| :---:|
|line1<br> line2<br> ...<br> lineN|

N is determined at runtime.

How can this be accomplished?

**Comment by sinyo-matu** [comment]
I found this can accomplish by adding a Table to TableCell.

Sorry for bothering!

closing

**Comment by GoWon7** [comment]
I think the right way to do this is to add multiple paragraphs to the cell or BreakType::TextWarpping to the paragraph's run, rather than creating a table in the cell.
