### ISSUE TITLE
Support Multi-Column Pages.

### ISSUE THREAD

**Issue by hayato-SMZ** [bokuweb/docx-rs#520]
I want to multi-column pages.

```
fn set_pages(columns: usize, docx: Doc) -> Doc{
  let mut section = docx_rs::SectionProperty::new();
  section.columns = columns;
  doc.document.section_property = section;
  return doc;
}
```
This confirms that I can change the settings for section properties for the entire document. However, the columns are not reflected.

I confirm that the columns can be changed by partially updating ```sectyon_property.rs``` and ```elements.rs```.

I know that I have not yet  Supported the ```Section```.
Can I send a pull request?

**Comment by bokuweb** [comment]
@hayato-SMZ 

Hi. Thanks for your proposal.

> Can I send a pull request?

Yes. please create a PR feel free.

FYI.  We need to support multi section. I'll consider about it later...

**Comment by hayato-SMZ** [comment]
Thank you.
I sent you a PR!
