### ISSUE TITLE
specVanish

### ISSUE THREAD

**Issue by gjblajian** [bokuweb/docx-rs#553]
## Is your feature request related to a problem? Please describe.

when importing a docx file the value of specVanish is not translated from the XML to the output

## Describe the solution you'd like

capture the specVanish value and pass it into the output

## Describe alternatives you've considered

N/A

## Additional context

https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.specvanish?view=openxml-2.8.1

you are capturing vanish but specVanish is not and they have slightly different meanings

**Comment by bokuweb** [comment]
@gjblajian Thank you. If you are ok, cloud you please provide docx file including `specVanish` ?

**Comment by gjblajian** [comment]
> @gjblajian Thank you. If you are ok, cloud you please provide docx file including `specVanish` ?

[3. U.S. Sub Name - Bylaws (1).docx](https://github.com/bokuweb/docx-rs/files/9901781/3.U.S.Sub.Name.-.Bylaws.1.docx)

**Comment by bokuweb** [comment]
@gjblajian Please try 0.0.276-rc31

**Comment by gjblajian** [comment]
thank you, @bokuweb
