### ISSUE TITLE
Special characters are being carried across using HTML entities vs unicode

### ISSUE THREAD

**Issue by gjblajian** [bokuweb/docx-rs#554]
## Describe the bug

html encoded values vs unicode values we have seen include &apos;, &quot; and &amp; are coming across in the text elements

## Reproduced step

import { readDocx } from 'docx-wasm'
const parsedDoc = readDocx(buf)
console.log(`parsedDoc: `, parsedDoc)

## Expected behavior

would prefer to see the values in the output as unicode e.g. &#8592; since many special characters do not actually have html entity translations (MS Word's start and end double quotes are different unicode entities [U+201C, U+201D])

## Actual behavior

html encoded values &apos;, &quot; and &amp; 

## Screenshots

![image](https://user-images.githubusercontent.com/5183939/198396817-a0deb5c7-69b5-4e6b-bc05-97f44b78bc69.png)

![image](https://user-images.githubusercontent.com/5183939/198396896-53242f3c-703f-4f60-a71e-ef793e22a8c9.png)

[Corporate Arbitration.docx](https://github.com/bokuweb/docx-rs/files/9883115/Corporate.Arbitration.docx)

## Desktop (please complete the following information)

- OS: [e.g. iOS] - Windows 11 & mac OS
- Browser [e.g. chrome, safari] - chrome
- Version [e.g. 22] - 0.0.276-rc28 [https://www.npmjs.com/package/docx-wasm]

**Comment by gjblajian** [comment]
Note that this bug does not ALWAYS happen for the quot or apos but seems to happen consistently for amp.

**Comment by bokuweb** [comment]
I'll check it later.

**Comment by bokuweb** [comment]
@gjblajian Please try 0.0.276-rc33

**Comment by gjblajian** [comment]
thank you, @bokuweb
