### ISSUE TITLE
isLgl

### ISSUE THREAD

**Issue by gjblajian** [bokuweb/docx-rs#555]
## Is your feature request related to a problem? Please describe.

when importing a docx file the value of isLgl is not translated from the XML to the output

## Describe the solution you'd like

capture the isLgl value/presence and pass it into the output

## Describe alternatives you've considered

N/A

## Additional context

https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.islegalnumberingstyle?view=openxml-2.8.1

**Comment by bokuweb** [comment]
@gjblajian Could you provide a docx file?

**Comment by bokuweb** [comment]
@gjblajian Please try docx-wasm@0.0.276-rc33

**Comment by gjblajian** [comment]
thank you @bokuweb
