### ISSUE TITLE
Read support

### ISSUE THREAD

**Issue by mominul** [bokuweb/docx-rs#575]
Hi, thanks for this crate! :heart: 

Do you have any intention to add `docx` reading capability to this crate? If anyone contributes reading support, will that be merged?

Thanks again!

**Comment by bokuweb** [comment]
reader is implemented. https://github.com/bokuweb/docx-rs/blob/main/docx-core/src/reader/document.rs
however this feature is undocumented and internal.

**Comment by madmaxio** [comment]
I'm also interested in reader, any plans for it in the future or it will stay in current state?

**Comment by mominul** [comment]
@bokuweb It seems reading support is implemented, shouldn't this be closed?
