### ISSUE TITLE
Not importing (or translating) linked style names

### ISSUE THREAD

**Issue by gjblajian** [bokuweb/docx-rs#587]
## Describe the bug

Style import is not including linked styles

## Reproduced step

Import a document with a linked style
![image](https://user-images.githubusercontent.com/5183939/206309647-0aa5333a-033d-4067-9506-f37f44cdec67.png)
The linked style is not in the imported styles
![image](https://user-images.githubusercontent.com/5183939/206309818-92dceba5-00a7-46bf-825d-f80b0f4b3266.png)

## Expected behavior

The imported styles should include the linked style

## Actual behavior

The linked style is not included

## Desktop (please complete the following information)

OS: [e.g. iOS]: Windows 11 [ and MacOS ]
Browser [e.g. chrome, safari]: chrome
Version [e.g. 22]: Version 108.0.5359.94 (Official Build) (64-bit)

**Comment by gjblajian** [comment]
@bokuweb any chance you might be able to add support for this?

**Comment by bokuweb** [comment]
@gjblajian For now 0.0.277-rc1 published. Could you please try it?

**Comment by gjblajian** [comment]
@bokuweb thank you
