### ISSUE TITLE
Images in headers/footers not importing

### ISSUE THREAD

**Issue by gjblajian** [bokuweb/docx-rs#608]
## Describe the bug

When an image is in the header or footer the image is not present in the JSON of readDocx()

## Reproduced step

1. create a document with an image in the header or footer
2. import that document using readDocx
3. image is not present

## Expected behavior

All images should be referenced in the JSON output of readDocx regardless of position in the document

## Actual behavior

Image is not present when it is in the header or footer

## Screenshots

N/A

## Desktop (please complete the following information)

N/A

**Comment by gjblajian** [comment]
@bokuweb could you please look into this? Thank you.

**Comment by bokuweb** [comment]
@gjblajian Sorry for late. I'm busy now... I'll improve it.

**Comment by arifd** [comment]
Images in headers (and probably footers) are also broken when created programmatically

```rs
use docx_rs::{Docx, Header, Paragraph, Pic, Run};
use std::{error::Error, io::Cursor};

fn main() -> Result<(), Box<dyn Error>> {
    let cat = Pic::new(include_bytes!("cat_min.jpg"));
    let header =
        Header::new().add_paragraph(Paragraph::new().add_run(Run::new().add_image(cat.clone())));
    let mut out = Vec::new();
    let docx = Docx::new()
        .header(header)
        .add_paragraph(Paragraph::new().add_run(Run::new().add_image(cat)));
    docx.build().pack(Cursor::new(&mut out))?;
    std::fs::write("/tmp/out.docx", &out)?;
    Ok(())
}
```
