### ISSUE TITLE
can't find `<w:ptab>`

### ISSUE THREAD

**Issue by Griklit** [bokuweb/docx-rs#619]
Hello, I tried to add ptab to the document.
But I can't find it.
Its XML structure is like this.
```xml
<w:r>
  <w:ptab w:relativeTo="margin" w:alignment="right" w:leader="none" />
</w:r>
```

**Comment by git-noise** [comment]
Hi, I pushed some initial support. Any feedback appreciated.

**Comment by git-noise** [comment]
@Griklit
Hello, I see you closed the issue, does the PR align with what you expected?
Thanks for your feedback
