### ISSUE TITLE
[Bug?] Runs don't respect newlines

### ISSUE THREAD

**Issue by arifd** [bokuweb/docx-rs#621]
## Describe the bug

```rs
Run::new().add_text("Hello\nworld")
```
will not produce text on two lines

## Reproduced step
```rs
use docx_rs::*;

pub fn main() -> Result<(), DocxError> {
    let path = std::path::Path::new("./hello.docx");
    let file = std::fs::File::create(path).unwrap();
    Docx::new()
        .add_paragraph(Paragraph::new().add_run(Run::new().add_text("Hello\nworld")))
        .build()
        .pack(file)?;
    Ok(())
}
```
## Expected behavior

![image](https://github.com/bokuweb/docx-rs/assets/2345750/b32d4523-78c2-47e6-b940-f96dfb353b9b)

## Actual behavior

![image](https://github.com/bokuweb/docx-rs/assets/2345750/cf3cc2c6-ef06-433d-a6f8-61e697005fed)

**Comment by GoWon7** [comment]
You need to use Run::add_break(BreakType::textWrapping) instead of \n

**Comment by arifd** [comment]
Oh, that's painful, but ok! Thanks for your help. :)
