### ISSUE TITLE
Strike is only available on run_property

### ISSUE THREAD

**Issue by soupslurpr** [bokuweb/docx-rs#647]
## Describe the bug

Hello, thanks for this crate. It is very useful. I see that strike() which to my knowledge should be for ~~strikethrough~~ is only in run_property and not for run itself.

## Reproduced step

Run::new().strike()

## Expected behavior

I think strike() should exist in run and not only run_property.

## Actual behavior

does not exist, while bold, italic, etc does exist.

## Desktop (please complete the following information)

- OS: Windows 11
- Version 0.4.7

**Comment by jvnkr** [comment]
+1

**Comment by git-noise** [comment]
Hi, sent a quick PR to tackle this one.
