### ISSUE TITLE
Section property not passing/translating type

### ISSUE THREAD

**Issue by gjblajian** [bokuweb/docx-rs#665]
@bokuweb 
## Is your feature request related to a problem? Please describe.
Yes, we need to be able to determine the type of section break being imported/parsed

The type defined in the XML is not being translated into the output of the readDocx() function

## Describe the solution you'd like
when a type is present in the Section Properties we would like the type to be translated into the readDocx() output

when the hghlighted type indicator is present in the XML
![image](https://github.com/bokuweb/docx-rs/assets/5183939/0e0eec7b-7655-44bb-b8d1-bffaf7478787)

we would like the output to contain the same type indicator in the json
![image](https://github.com/bokuweb/docx-rs/assets/5183939/c4e0a4d8-8195-4281-b7c0-6b5cd4f8513a)

## Describe alternatives you've considered
N/A

N/A

**Comment by intellinui** [comment]
@bokuweb any help would be appreciated as different section types behavior differently.

**Comment by bokuweb** [comment]
I'll fix it later

**Comment by intellinui** [comment]
@bokuweb thank you thank you thank you

**Comment by bokuweb** [comment]
```
<xsd:restriction base="xsd:string">
  <xsd:enumeration value="nextPage"/>
  <xsd:enumeration value="nextColumn"/>
  <xsd:enumeration value="continuous"/>
  <xsd:enumeration value="evenPage"/>
  <xsd:enumeration value="oddPage"/>
</xsd:restriction>
```

**Comment by bokuweb** [comment]
@gjblajian @intellinui Please try 0.0.278 rc26
