### ISSUE TITLE
Leftover dbg!() macro at docx-rs-0.4.13\src\reader\mod.rs:478:17

### ISSUE THREAD

**Issue by ZizoAdam** [bokuweb/docx-rs#702]
## Describe the bug

There's a leftover debug statement at docx-rs-0.4.13\src\reader\mod.rs:478:17

## Reproduced step

1. Call read_docx with a file that contains images
2. Look at stdout

## Screenshots
![image](https://github.com/bokuweb/docx-rs/assets/124168668/d1ffdb10-a810-43ff-888f-5d7350a3f56b)

**Comment by bokuweb** [comment]
https://github.com/bokuweb/docx-rs/pull/704
